### PR TITLE
Replace webxdc api integration (old, replaced with #215)

### LINKED ISSUE #79: auto-update appstore.xdc in-place
needs: https://github.com/deltachat/deltachat-core-rust/issues/4480

### PR DESCRIPTION
**Pull request by Septias**
**This PR is replaced with #215**

Uses the new API to replace the store.
To test this I suggest using a local version of the deltachat-desktop which checks out the PR introducing the API. Otherwise, it will not work.

As to be expected, the desktop doesn't handle these replacements correctly atm. Instead of actually replacing the message a new message is shown in the chat which also shares the same time. Sending messages in the old message works just fine, but sending updates from the new ones produces this error:

`DC: /home/sebastian/.cargo/git/checkouts/deltachat-core-rust-632648ad67f90089/3cfbac5/src/receive_imf.rs:288: receive_imf cannot update status: receive_status_update: status message has no parent..` 

close #79

### CODE REVIEW

**Comment by Septias** [comment]
> > Sending messages in the _old_ message works just fine, but sending updates from the old ones produces this error:
> 
> Should I read this as "sending messages in the new message works just fine"?

Otherway round. The massages added by dc-desktop a flawed.

**Comment by Septias** [comment]
I guess the local storage of the app gets restored, making it impossible to notice something because of a vanished store...
We can use the `update received` event to unlock the app again, but if the messages come in out of order, the replacement has not taken place yet when the frontend is unlocked again. Maybe some core-event/webxdcUpdate could be sent to make this deterministic?

**Comment by Septias** [comment]
True that can be done. It might be interesting to consider a dedicated event at some point though to improve the overall webxcd standard capabilities. But that is for now out of scope I believe.

**Comment by Septias** [comment]
It seems like the localStorage is not recovered in the new webxdc instance at the moment. Just to be clear - restoring local storage for webxdcs is the plan, right? @link2xt @Simon-Laux @hpk42

**Comment by hpk42** [comment]
Yes, a replaced xdc attachment should still lead to re-using the localstorage state
of the previous xdc app.

**Comment by Septias** [comment]
@Simon-Laux Atm, the desktop still shows two messages (at least my delta chat-desktop-git arch package). What is the status to fix this?

**Comment by Simon-Laux** [comment]
> at least my deltachat-desktop-git arch package

that does not use the git core, it uses the core that dc desktop master uses so still 1.107 at the time

**Pull request closed without merging**
