### PR TITLE
improvement: frontend layout

### LINKED ISSUE #163: frontend layout improvements
first of all, thanks lot for making the store to what it is now!

here are some suggestions for layout improvements:

- use fewer lines and waste fewer space. in general, a rule of thumb in design (esp. if you are not a designer :) is to use fewer lines :)

- the "arrow down" for expanding is not self explaining.  
more common icons for such things are "plus/minus" or a "triange that rotates by 90 degrees". (the "arrow down" icon is also a not-so-good choice as "arrow down" is also used for "download", making things unnecessary hard eg. to explain).  
however, i would not go for a symbol that need explanations at all, instead, just call it what it is - "Details" (and if expanded, "Hide Details")

- ~~the title looks cluttered. there are three different left-alignment-postions (title, search, items). a centered title looks better here (as already suggested in some chats)~~
EDIT: thinking it over, the title is not needed at all. it is just a repetition of what is shown in the window title and we also usually do not show big titles elsewhere in comparable tools. i adapted the screenshot and also slightly changed the placeholder

- for the "i": the version is mostly debug information and the "reload" is hard to discover, so i assume, this is usually not a primary function anyways. therefore, i would move the whole dialog content as simple text to the footer, centered.  
_if_ the "update" is really important, move it as a text-only string as "Last Update ... Update now" with a smaller font between search field and items

- add a placeholder to the search text

here is a rough mockup. at the same size, the new layout contains quite some more characters per line and 1.5 more app items while still looking similar airy:

**before / after:**

 &nbsp; &nbsp; &nbsp;  

<details>
<summary>Abandoned layouts</summary>

<br>(the title is not needed at all. it is just a repetition of what is shown in the window title and we also do not show big titles elsewhere in webxdc's)
</details>

(as i had no good idea how to play around with html and real data, i did that in gimp, but i think, you get the idea. a bit of space is missing between the download/share buttons and the text. "Details" should have the same font size as the description and of course, things should be aligned properly :)

for the "share button", which is more a "forward button": i suggest to use the "swooth variation" (  ) that is also used in whatsapp/telegram/signal at similar places and is known by users. there is no need to "invent" a new icon by adding a 90-degrees chipped-line-arrow.

maybe also make the icons ~10% smaller in width/height, so that there is a better visual balance to the buttons on the right. but that is nitpicking and should be tested (i could not really do that due to lack of html access with test data)

image vs. text buttons was already discussed, i  think, with the correct icons, we can give image buttons a try - also as moving to text buttons would require more re-layouting, and this issue is meant for easy improvements.

### LINKED ISSUE #168: missing hint if there are no search results
if nothing is found, a hint should be printed, maybe repeating the search term.

> No results for \"abcdef\" - Show all

"Show all" could be a link that ends the search.

maybe also hide the footer in case there are no results (or move it down so that it is clear it  does not belong to the search). otherwise, ppl will probably always hit "Update now" as this is the only remaining button

### LINKED ISSUE #169: "There are no apps" is a weird wording
Screenshot 2023-07-14 at 18 06 59

please go for sth. more usual if no apps were found on search entry, eg. go for the suggestion at https://github.com/webxdc/store/issues/168

i'd also still consider to hide the footer in this case, it looks as if this is a primary actionable item as it is the most outstanding item in this case. alternatively, maybe it is sufficient to make the button less outstanding as suggested at https://github.com/webxdc/store/pull/167#issuecomment-1635911873

### PR DESCRIPTION
**Pull request by Septias**
closes #163 
closes #168 
closes #169

### CODE REVIEW

**Comment by Septias** [comment]
As an intermediate state with reduced space usage:
image

**Comment by Septias** [comment]
This is how it looks with separating lines:
image

**Comment by Septias** [comment]
Another mockup with the update button at the bottom:
image

**Comment by Septias** [comment]
I still like the bordered view that can be seen in the first image even though it is a little more cluttered because it makes the other elements (search and update) more natural. But there are still a lot of small changes that can make a huge difference so in the end it's just about fiddling around with it a bit. 
Please make suggestions and refer to the different pictures I posted so we can together work towards a nice layout :)

**Comment by r10s** [comment]
> Another mockup with the update button at the bottom:
> 

my approval refers to this (the third) version; however, the "button" layout is a bit weird with the text as there is no "actionable title". please use normal text plus a (blue) link "Update now", so, sth. as

> 

(the link color + size should be same as the more/less links)

**Review by r10s — APPROVED** [review]
from the images, this looks good to me, apart from the footer, see comment above. i did not checked the code

**Comment by Septias** [comment]
> 
> 
> Placeholder is selectable if you start dragging outside the field. I think it is a bug, such selected placeholder cannot even be deleted. Could this be made a real HTML field placeholder?

it actually is

**Comment by Septias** [comment]
The line above was added by me later as otherwise there is no clear separation between the search bar and the apps

**Comment by Septias** [comment]
image

**Comment by Septias** [comment]
Footer is now at the bottom and the text is changed so I added the two issues #168 and #169 as closed @r10s 

image

**Comment by r10s** [comment]
thanks a lot!

- empty-search-hint and footer looks much better

- the icon are not much smaller, or?

idea was to make the lower border of the icon roughly same position as baseline of "More". and the upper border of the icon roughly same position as ascent height of title.

maybe try out 1.9em or 2.0em?

then, check that default size of desktop shows about 26 characters (this is a size that is also reachable with most phones) and/or adapt xdcget docs to match the layout so that in most cases no ellipse is shown

note, that the first line must not be repeated in the "More" view

nb: i am afk today, so feel free to merge to move forward if things block otherwise, do not wait for me :) these are already great improvements, and we can always do a follow up pr

**Comment by Septias** [comment]
So you don't want the icon to be centered?

**Comment by Septias** [comment]
image

This feels way too small for me for some primary action buttons.

**Comment by r10s** [comment]
wait, i am talking about the left app-icons, the right action-icons are fine so far 😅

and yes, things should stay vertically centered, just a little bit smaller

**Comment by Septias** [comment]
image

**Comment by r10s** [comment]
yeah, sth like that, +1, i think, this is good enough for now (final tweaks are hard to do over pr comments, it is better when one sees the result directly)

thanks a lot!

**Pull request merged**
