### PR TITLE
Add livecycle buttons

### LINKED ISSUE #91: re-opening webxdc calls sendToChat() directly
after sharing 2 webxdc and closing the store: on re-opening  the store, the store closes immediately and directly shows the the "share to" dialog

it seems as if somehow the "sendToChat" click is re-executed when re-opening

confirmed by @Simon-Laux and @hpk42 in chat

### PR DESCRIPTION
**Pull request by Septias**
This PR adds livecycle buttons for the state of the xdc.

image

From top to bottom in the image these states are represented:
- Read to download
- Downloading
- Download error
- Received (ready to forward)

Now only pressing forward will _actuall_ send the webxdc to some chat.

closes #91

### CODE REVIEW

**Comment by hpk42** [comment]
an interesting improvement -- I didn't test this PR myself (and won't today as things stand) but would be fine to merge it as it improves the current state. 
Note however that there also is the "update available" state -- i.e. you can share the current version of an app (it's downloaded) but there also is a new version available.

**Comment by Septias** [comment]
Yeah I know @hpk42 , I will add that as soon as updating is actually supported

**Comment by Septias** [comment]
> I think the icons and colors are fine, but I recommend putting text in the button as well, not only the icon
> 
> ex. beside the icon: Download, Downloading..., Error, Share

I believe the text will just make it more clumbsy while not adding any benefit.

**Review by adbenitez — APPROVED** [review]
I still think it would be nicer if the buttons have text, but it is also better this than the not working state of before so approving, we can improve on top later anyway

**Pull request merged**
