### PR TITLE
use a tiled background

### PR DESCRIPTION
**Pull request by r10s**
the existing one does not look good in practise, the close-to-white, more as a bug, i was wrong with my initial assumptions :)

if we like that, we can adapt the background tiles to some typical webxdc icons (triska, calendar, ...) instead of delta+mail
but for now, this seems good enough and an improvement to before

alternative might be to use a plain-white background

moreover, i optimized the icon for byte size, 256x256, less colors, oxipng

@Septias i think, the placement of the .svg in the public folder is not good as that gets probably included in the webxdc - i did not change that in this pr, however

before/after:

### CODE REVIEW

**Comment by r10s** [comment]
> alternative might be to use a plain-white background

let's leave this for reference, i do another one going for plain white. this is closer to the already existing one

**Comment by Simon-Laux** [comment]
I like the idea of showing app icons, here some inspiration what other apps stores use:
 Bildschirmfoto 2023-07-22 um 15 42 49

**Comment by Simon-Laux** [comment]
I think the main problem is that the icon is currently off-center

**Comment by r10s** [comment]
> I like the idea of showing app icons, here some inspiration what other apps stores use

nice, thanks for the images. however, these collages are not an icon (they contain lots of icons, of course :)

> I think the main problem is that the icon is currently off-center

why is that an problem?

we could have eg. sth. as above and a collage of monochrome webxdc icons in the background

**Comment by Simon-Laux** [comment]
> nice, thanks for the images. however, these collages are not an icon (they contain lots of icons, of course :)

Icons should not have that much detail anyway. So I'm not sure about a textured background in general, still the idea of a collage of many app icons/banners can be used in marketing or/and the webxdc store website.

> why is that an problem?

I does not look good to my eyes, not enough space at the right, with the wallpaper it was moved a bit but with the bright or white background it becomes apparent to my eyes at least. also looking center does not mean that it needs to be in the center, for example the logo of google is not completely geometrical and round.

**Comment by r10s** [comment]
> I does not look good to my eyes, not enough space at the right, with the wallpaper it was moved a bit, so it's better, but with the bright or white background it becomes apparent to my eyes at least. also looking center does not mean that it needs to be in the center, for example the logo of google is not completely geometrical and round.

ahh, i see, you just wanted to point out a bug _in_ the icon. i thought about sth. more general :)

note, that the icon is more meant as a draft, to get an idea, an impression

**Pull request closed without merging**
