### PR TITLE
chore: Split description and summary by newline

### LINKED ISSUE #177: split summary from description
The description fields contain "\n" separated lines: 

- the first line is the "short summary" 
- the remaining lines are the long-description. 

The UI should process it this way.

### PR DESCRIPTION
**Pull request by Septias**
image

A dot would be nice at the end of every sentence. This can be added by the frontend but I believe adding it to the repo descriptions is much cleaner.

close #177

### CODE REVIEW

**Comment by r10s** [comment]
> A dot would be nice at the end of every sentence

why?

the dot in comparable, very short, fields is often left out in modern layouts - and it was tentatively always left out if the summaries are no full sentences

Some consider a dot at the end of a statement to be an attack.

**Comment by Septias** [comment]
Okay, if you like it that way you can approve - if there is nothing else bothering you ofcause.

**Comment by r10s** [comment]
btw, in the last row of the screenshot: why is the spinner shown beside the "forward icon"? is that an update?

**Comment by Septias** [comment]
I don't know if I understood correctly, but the reasoning for this layout is that you can still forward the app until the new version arrived. (Keep sharing an older version)

**Comment by r10s** [comment]
> I don't know if I understood correctly, but the reasoning for this layout is that you can still forward the app until the new version arrived. (Keep sharing an older version)

makes totally sense, i do not question that.

i just wanted to note that the "white update spinner" looks far better, see reasoning above

**Pull request merged**
